<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Service Reports PDF</title>

    <style>
        @page { margin: 40px 25px; }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 0;
            background-color: #fff;
        }

        h2, h4, p {
            margin: 0;
            padding: 0;
        }

        header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }
        .table {
            width: 100%;
            margin-top: 15px;
            border-collapse: collapse;
        }

        .table th,
        .table td {
            padding: 8px;
            border: 1px solid #dee2e6;
            vertical-align: top;
        }

        .table thead th {
            background-color: #f8f9fa;
            font-weight: bold;
        }

        .table-striped tbody tr:nth-of-type(odd) {
            background-color: #f9f9f9;
        }

        .table-bordered {
            border: 1px solid #dee2e6;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .text-muted {
            color: #6c757d;
        }

        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #555;
            border-top: 1px solid #ccc;
            padding-top: 4px;
        }

        .total-row {
            font-weight: bold;
            background-color: #f1f1f1;
        }

        .container {
            width: 95%;
            margin: auto;
        }

        .mt-2 { margin-top: 10px; }
        .mt-3 { margin-top: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h2>Autocare Workshop</h2>
            <h4>Service Reports</h4>
            <p class="text-muted mt-2">
                Generated on: {{ now()->setTimezone('Asia/Kolkata')->format('d M Y, h:i A') }}
            </p>
        </header>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Job ID</th>
                    <th>Vehicle</th>
                    <th>Customer</th>
                    <th>Staff</th>
                    <th>Status</th>
                    <th class="text-right">Amount (₹)</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($reports as $report)
                    <tr>
                        <td>{{ $report->job_id ?? 'N/A' }}</td>
                        <td>{{ $report->vehicle->registration_no ?? 'N/A' }}</td>
                        <td>{{ $report->vehicle->customer->name ?? 'N/A' }}</td>
                        <td>{{ $report->staff->name ?? 'N/A' }}</td>
                        <td>{{ ucfirst($report->status ?? 'Pending') }}</td>
                        <td class="text-right">
                            ₹{{ number_format($report->amount ?? 0, 2) }}
                        </td>
                        <td>{{ optional($report->created_at)->setTimezone('Asia/Kolkata')->format('d M Y') }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="text-center text-muted">No service reports available.</td>
                    </tr>
                @endforelse
            </tbody>

            @if($reports->count() > 0)
            <tfoot>
                <tr class="total-row">
                    <td colspan="5" class="text-right">Total Amount:</td>
                    <td colspan="2" class="text-right">
                        ₹{{ number_format($reports->sum('amount'), 2) }}
                    </td>
                </tr>
            </tfoot>
            @endif
        </table>

        <footer>
            <p>Autocare Workshop | Generated by {{ Auth::user()->name ?? 'Admin' }}</p>
        </footer>
    </div>
</body>
</html>
